services:
  - type: web
    name: ape-monitoring
    runtime: node
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
